write("Set program name: ")
local ProgramName = tostring(read())
write("\n")
write("Set PasteBin text ID: ")
local PasteBin_Text_ID = tostring(read())
write("\n")
shell.run("delete", ProgramName)
write("Deleted!\n")
shell.run("pastebin", "get", PasteBin_Text_ID, ProgramName )
write("Downloaded!\n")